import 'package:get/get.dart';

class SoftStarterLocale extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "fr": {
          "ask.confirm":"Etes vous sûr de confirmer cette opération ?",
          "confirm":"Confirmer",
          "year":"Année",
          "loading":"Chargement",
          "credit":"Crédit",
          "customers_credit":"Crédit des Clients",
          "print.prices": "Imprimer les prix",
          "product.list.title": "Liste des Produits",
          "my.pricelists": "Mes Listes de Prix",
          "my.listing": "Liste des prix",
          "list.prices": "Voir les listes de prix",
          "commercial": "Commerciale",
          "commercial.sub": "Gestion Commerciale",
          "welcome": "Bienvenue",
          "to_our_service": "à notre service",
          "slogan": "Vendez plus, gagnez beaucoup !",
          "get_started": "Commencer",
          "login": "Se connecter",
          "login_text": "Entrez votre email et votre mot de passe",
          "password_forgot": "Mot de passe oublié ?",
          "not_yet_user": "Vous n'avez pas encore de compte ?",
          "signup": "S'inscrire",
          "signup_text": "Entrez vos informations personnelles",
          "create": "Créer un compte",
          "forget": "Mot de passe oublié",
          "forgot_text":
              "Entrez votre adresse email pour récupérer le mot de passe",
          "wrongemailaddress": "Le format de l'adresse email est invalide",
          "emptypassword": "Le mot de passe ne peut pas être vide",
          "mailempty": "L'adresse email ne peut pas être vide",
          "shortpassword":
              "Le mot de passe doit contenir au moins 6 caractères",
          "nouserfound":
              "Aucun compte n'a été trouvé pour cette adresse email !",
          "wrongpassword": "Le mot de passe ne correspond pas à ce compte !",
          "fullname_length_error": "Veuillez entrer votre nom complet",
          "otherway": "Ou via d'autres méthodes",
          "success": "Opération réussie",
          "registred.email":
              "Votre compte a été créé avec succès...\nUn email de confirmation a été envoyé à votre adresse email.",
          "registred.social": "Votre compte a été créé avec succès...",
          "verificationmail.title": "Email non vérifié",
          "erroraccountexist": "Cette adresse email est déjà enregistrée !",
          "verificationmail.body":
              "Votre compte n'a pas encore été activé !\nVoulez-vous envoyer un email de vérification ?",
          "find_product": "Trouver des produits",
          "search": "Rechercher",
          "bestselling": "Les plus vendus",
          "products": "Produits",
          "categories": "Catégories",
          "general": "Général",
          "promotion": "Promotion",
          "Last Name": "Nom de famille",
          "First Name": "Prénom",
          "Wilaya": "Wilaya",
          "City": "Daira",
          "Profile": "Profil",
          "errorLastName": "Veuillez saisir votre nom",
          "errorFirstName": "Veuillez saisir votre prénom",
          "errorWilaya": "Veuillez sélectionner votre wilaya",
          "errorCity": "Veuillez sélectionner votre ville",
          "errorProfile": "Veuillez sélectionner votre profil",
          "profilesaved":
              "L'opération d'enregistrement a été effectuée avec succès. Vous allez être redirigé vers la page d'accueil !",
          "unknownerror":
              "L'opération d'enregistrement a rencontré un problème. Merci de réessayer plus tard.",
          "error": "Erreur",
          "userdisabled": "Votre compte a été désactivé !",
          "unknown.error":
              "Une erreur est survenue, veuillez réessayer plus tard",
          "email.used": "L'adresse email associée est déjà utilisée !",
          "new.client": "Nouveau client",
          "edit.client": "Modifier client",
          "name.client": "Nom du client",
          "type.client": "Type de client",
          "mobile.client": "Téléphone",
          "editer.client": "Modifier client",
          "error.name.client": "Le nom du client est obligatoire",
          "position.disabled.do.you.want.enable":
              "L'application n'a pas l'autorisation pour obtenir votre position actuelle. Voulez-vous l'autoriser ?",
          "position.forever.disabled":
              "Les autorisations de localisation sont définitivement refusées. Nous ne pouvons pas demander d'autorisations.",
          "sendmail": "Envoyer un mail",
          "mail.not.verified": "Courriel non vérifié",
          "save": "Enregistrer",
          "print": "Imprimer",
          "empty.items": "Vider la commande",
          "close": "Fermer",
          "add": "Ajouter",
          "are.you.sure.to.ignore": "Êtes-vous sûr d'ignorer cette commande ?",
          "are.you.sure.to.quit.order":
              "Êtes-vous sûr de quitter cette commande ?",
          "you.are.disconnected": "Vous avez un problème de connexion internet",
          "quantity.not.available":
              "Un ou plusieurs produits ne sont pas disponibles en stock !",
          "successfully.saved":
              "Votre opération a été enregistrée avec succès.",
          "error.saved":
              "Votre opération ne s'est pas déroulée correctement. Merci de réessayer.",
          "succefully.saved": "Votre opération s'est effectuée avec succès",
          "printer.config.title": "Configuration imprimante",
          "no printer!": "Aucune imprimante n'est connectée",
          "no.printer.found": "Aucune imprimante trouvée !",
          "searching": "Recherche en cours...",
          "printer.size": "Format papier",
          "cities": "Villes",
          "edit.profile": "Editer le profil",
          "rescan": "Recherche à nouveau",
          "printing": "Impression en cours !",
          "print.not_available": "Imprimante non trouvée !",
          "bluetooth.problem":
              "Problème de liaison Bluetooth avec l'imprimante",
          "printer.pb.link": "Problème de liaison Bluetooth avec l'imprimante",
          "printer.settings": "Configuration imprimante",
          "encoding": "Encodage",
          "size.subtitle": "Taille du variant",
          "small": "Petite",
          "middle": "Moyenne",
          "saturday": "Samedi",
          "sunday": "Dimanche",
          "monday": "Lundi",
          "tuesday": "Mardi",
          "thursday": "Mercredi",
          "wednesday": "Jeudi",
          "friday": "Vendredi",
          "print.client.balance": "Impr historique crédit",
          "mywarehouses": "Mes dépôts",
          "disconnect": "Se déconnecter",
          "about": "À propos",
          "reception.product": "Réception des produits",
          "print.stock": "Imprimer l'état des stocks",
          "client.more.infos": "Plus d'informations",
          "my.promotions": "Mes promotions",
          "promo.config": "Configuration des promotions",
          "to": "à",
          "edit": "Modifier",
          "new": "Nouveau",
          "new.promotion": "Nouvelle promotion",
          "edit.promotion": "Modifier promotion",
          "description": "Description",
          "describe.your.promo.here": "Description de la promotion",
          "discount_price": "Sur le prix",
          "discount_total": "Sur le total",
          "add.product": "Ajouter un produit ou une variante",
          "product": "Produit",
          "variant": "Variante",
          "discount": "Réduction",
          "minimum": "Minimum",
          "list.orders": "Liste des commandes",
          "send": "Envoyer à",
          "export": "Exporter en PDF",
          "print.invoices.today": "Imprimer les commandes",
          "print.goods.today": "Imprimer récap. prod",
          "last.name": "Nom de famille",
          "first.name": "Prénom",
          "phone": "Téléphone",
          "errorPhone.empty": "Le numéro est obligatoire",
          "errorPhone.notvalide": "Ce numéro n'est pas valide",
          "quantity": "Quantité",
          "orders.ready.toship": "Commandes en attente",
          "generate.bt": "Générer un bon de transfert",
          "refresh": "Actualiser",
          "confirm.bt": "Confirmer le bon de transfert",
          "bl.ready": "Livraisons",
          "bt.ready": "Transferts",
          "location.stock": "Stock actuel",
          "dispo.only": "Disponible",
          "alert.only": "En alerte",
          "empty.only": "En rupture",
          "all": "Tout",
          "transfer.is.ready.to.confirm":
              "Le bon de transfert est prêt à être validé",
          "transfer.confirmed":
              "Le bon de transfert a été confirmé avec succès",
          "orders.to.ship": "Commandes à livrer",
          "orders.to.track": "État des commandes",
          "settings": "Paramètres",
          "track.order": "Suivi de commande",
          "state.new": "Nouvelle",
          "state.taken": "En préparation",
          "state.in_way": "En route",
          "state.shipped": "Livrée",
          "state.expired": "Expirée",
          "state.paid": "Payée",
          "state.partially_paid": "Payée part.",
          "state.cancelled": "Annulée",
          "delivery.planned.to": "Livraison estimée",
          "client.cash": "Encaisser",
          "client.cash.all": "Encaissement Total",
          "client.delivery": "Livrer",
          "cash.collect": "Encaissé",
          "client.cash.delivery": "Livrer et encaisser",
          "total": "Total",
          "delivery.proof": "Preuve de livraison",
          "cash.window": "Encaissement d'argent",
          "money": "Encaissement",
          "this.order": "Cette commande",
          "other.solde": "Autre solde",
          "amount.must.be.bellow.to": "Le montant doit être inférieur à ",
          "zero.not.allowed": "La valeur 0 n'est pas autorisée",
          "adjust": "Ajuster",
          "saleprice": "Prix de vente",
          "sale": "Vente",
          "visit": "Visiter",
          "apply.adjust": "Appliquer l'ajustement",
          "price.is.updated.if.changed": "Les prix sont mis à jour si changés",
          "info": "Information",
          "Language": "Langue",
          "Language_system": "Langue de l'application",
          "Notifications": "Notifications",
          "notifications_alert": "Alertes du système",
          "Messages": "Messages",
          "discussion_message": "Messages avec les utilisateurs",
          "Theme": "Thème",
          "theme_system": "Thème de l'application",
          "current_version": "Version actuelle",
          "pormo.config": "Configuration des promotions",
          "your_warehouse": "Mes dépots de livraison",
          "disconnect_account": "Déconnection de compte",
          "dashboard": "Tableau de Boards",
          "turnover": "Réalisation",
          "category_turnover": "Réalisation par categorie",
          "customer_classes": "Répartition des mes Clients",
          "Disponible": "Disponible",
          "others": "Autres",
          "please select ...": "Selctionner ...",
          "type_pv": "Type de PV",
          "sell": "Vendre",
          "bluetooth": "Bluetooth",
          "Cart": "Cart",
          "Pcs": "Pcs",
          "Paquet": "Paquet",
          "Caisse": "Caisse",
          "OK": "OK",
          "read": "vu",
          "unread": "reçu",
          "new_order_placed": "Commande placée au client",
          "order_inpreparing": "Commande est en préparation au dépot",
          "order_inway": "Commande est encours de livraison",
          "order_delivered": "Commande est livrée",
          "order_cashed": "Commande Encaissée",
          "order_cashed_partially": "Commande Partiellement payée",
          "cash.money": "Montant à encaisser",
          "empty.not.allowed": "Valeur vide n'est pas autorisée",
          "cash.erase.action": "Etes vous sure d'encaisser la totalité",
          "delivery.without.cash": "Etes vous sure de livrer sans encaisser",
          "receivables": "Créances des clients",
          "customers_balance": "Clients avec leurs soldes",
          "delivery.proof.is.required": "Preuve de livraison est obligatoire",
          "my.coupons": "Mes coupons",
          "coupons.config": "Configuration des coupons",
          "more.than": "Supérieur à",
          "use.coupon": "Utiliser Coupon",
          "coupon.window": "Entrer Votre Coupon",
          "description.coupon":
              "Le coupon sert à réduire le montant de la commande, veuillez introduire votre code coupon maintenant",
          "ex.coupon": "ex: ABCDEFGH",
          "my.actors": "Mes acteurs",
          "actor.config": "Voir les acteurs et configuration",
          "coupon": "Coupon",
          "no.more.coupon.available": "Il n'y a plus de coupons",
          "no.coupon.found": "Aucun coupon correspond à ec code",
          "order.amount.must.be.more.than": "Commande doit être supérieur à ",
          "new.coupon": "Nouveau coupon",
          "coupon.settings": "Configuration du coupon",
          "code": "Code",
          "count": "Nombre",
          "modification.window": "Fenêtre de modification",
          "max.value": "Valeur maximum est ",
          "comma.not.allowed": "La virgule n'est pas autorisée",
          "optimize.route": "Optimiser itinéraire",
          "maps.route": "Aller à la maps",
          "cancel": "Annuler",
          "day.only": "Jour Visite",
          "reason.no.sale": "Raisons de non-vente",
          "status.orders": "Etats des commandes",
          "renew.order.question": "Etes vous sure de renouveller la commande ?",
          "confirmation.renew": "Confirmation",
        },
        "en": {
          "confirm":"Confirm",
          "year":"Year",
          "loading":"Loading",
          "credit":"Credit",
          "customers_credit":"Customers Credit",
          "commercial": "Commercial",
          "commercial.sub": "Commercial Management",
          "welcome": "Welcome",
          "to_our_service": "to our service",
          "slogan": "Sell more, earn more!",
          "get_started": "Start",
          "login": "Login",
          "login_text": "Enter your email and password",
          "password_forgot": "Forgot password?",
          "not_yet_user": "Don't have an account yet?",
          "signup": "Sign Up",
          "signup_text": "Enter your personal information",
          "create": "Create Account",
          "forget": "Forgot password",
          "forgot_text": "Enter your email address to recover the password",
          "wrongemailaddress": "The email address format is invalid",
          "emptypassword": "Password cannot be empty",
          "mailempty": "Email address cannot be empty",
          "shortpassword": "The password must contain at least 6 characters",
          "userfound": "No account was found for this email address!",
          "wrongpassword": "The password does not match this account!",
          "fullname_length_error": "Please enter your full name",
          "otherway": "Or via other methods",
          "success": "Operation successful",
          "registered.email":
              "Your account has been successfully created...\nA confirmation email has been sent to your email address.",
          "registered.social": "Your account has been successfully created...",
          "verificationmail.title": "Email not verified",
          "erroaccountexist": "This email address is already registered!",
          "verificationmail.body":
              "Your account has not been activated yet!\nDo you want to send a verification email?",
          "find_product": "Find Products",
          "search": "Search",
          "bestselling": "Best Selling",
          "products": "Products",
          "categories": "Categories",
          "general": "General",
          "promotion": "Promotion",
          "pormo.config": "Configure Promotions",
          "Last Name": "Last Name",
          "First Name": "First Name",
          "Wilaya": "Wilaya",
          "City": "Daira",
          "Profile": "Profile",
          "errorLastName": "Please enter your last name",
          "errorFirstName": "Please enter your first name",
          "errorWilaya": "Please select your wilaya",
          "errorCity": "Please select your city",
          "errorProfile": "Please select your profile",
          "profilesaved":
              "The save operation was successful. You will be redirected to the homepage!",
          "unknownerror":
              "The save operation encountered a problem. Please try again later.",
          "error": "Error",
          "userdisabled": "Your account has been disabled!",
          "unknown.error": "An error has occurred, please try again later",
          "email.used": "The associated email address is already in use!",
          "new.customer": "New customer",
          "edit.client": "Edit client",
          "name.client": "Client name",
          "type.customer": "Type of customer",
          "mobile.client": "Phone",
          "edit.customer": "Edit customer",
          "error.name.client": "Client name is required",
          "position.disabled.do.you.want.enable":
              "The app does not have permission to get your current location. Do you want to allow it?",
          "position.forever.disabled":
              "Location permissions are permanently denied. We cannot request permissions.",
          "sendmail": "Send mail",
          "mail.not.verified": "Email not verified",
          "save": "Save",
          "print": "Print",
          "empty.items": "Empty Order",
          "close": "Close",
          "add": "Add",
          "are.you.sure.to.ignore": "Are you sure to ignore this command?",
          "are.you.sure.to.quit.order": "Are you sure to quit this command?",
          "you.are.disconnected": "You have an internet connection problem",
          "quantity.not.available":
              "One or more products are not available in stock!",
          "successfully.saved": "Your operation has been saved successfully.",
          "error.saved":
              "Your operation did not go through correctly. Please try again.",
          "printer.config.title": "Printer Configuration",
          "no printer!": "No printer is connected",
          "no.printer.found": "No printer found!",
          "searching": "Searching...",
          "printer.size": "Paper Size",
          "cities": "Cities",
          "edit.profile": "Edit Profile",
          "printing": "Printing!",
          "print.not_available": "Printer not found!",
          "bluetooth.problem": "Bluetooth connection problem with the printer",
          "printer.pb.link": "Bluetooth link problem with printer",
          "printer.settings": "Printer Settings",
          "encoding": "Encoding",
          "size.subtitle": "Variant size",
          "small": "Small",
          "middle": "Middle",
          "saturday": "Saturday",
          "sunday": "Sunday",
          "monday": "Monday",
          "tuesday": "Tuesday",
          "thursday": "Wednesday",
          "wednesday": "Thursday",
          "friday": "Friday",
          "print.client.balance": "Print Credit History",
          "mywarehouses": "My repositories",
          "disconnect": "Disconnect",
          "rescan": "Search again",
          "about": "About",
          "reception.product": "Receipt of products",
          "print.stock": "Print stock status",
          "client.more.infos": "More information",
          "my.promotions": "My promotions",
          "promo.config": "Promotions configuration",
          "to": "to",
          "edit": "Edit",
          "new": "New",
          "new.promotion": "New promotion",
          "edit.promotion": "Edit promotion",
          "description": "Description",
          "describe.your.promo.here": "Description of the promotion",
          "discount_price": "On price",
          "discount_total": "Out of total",
          "add.product": "Add Product or Variant",
          "product": "Product",
          "variant": "Variant",
          "discount": "Discount",
          "minimum": "Minimum",
          "list.orders": "List of orders",
          "send": "Send to",
          "export": "Export to PDF",
          "print.invoices.today": "Print Invoices",
          "print.goods.today": "Print Goods Summary",
          "last.name": "Last name",
          "first.name": "First name",
          "phone": "Phone",
          "errorPhone.empty": "The number is required",
          "errorPhone.notvalide": "This number is not valid",
          "quantity": "Quantity",
          "orders.ready.toship": "Pending orders",
          "generate.bt": "Generate transfer voucher",
          "refresh": "Refresh",
          "confirm.bt": "Confirm transfer voucher",
          "bl.ready": "Deliveries",
          "bt.ready": "Transfers",
          "location.stock": "Current stock",
          "available.only": "Available",
          "alert.only": "Alert",
          "empty.only": "Out of stock",
          "all": "All",
          "transfer.is.ready.to.confirm":
              "The transfer voucher is ready to be validated",
          "transfer.confirmed":
              "The transfer voucher has been successfully confirmed",
          "orders.to.ship": "Orders to ship",
          "orders.to.track": "Orders Status",
          "settings": "Settings",
          "track.order": "Order Tracking",
          "state.new": "New",
          "state.taken": "In preparation",
          "state.in_way": "In the way",
          "state.shipped": "Shipped",
          "state.expired": "Expired",
          "state.paid": "Paid",
          "state.partially_paid": "Partially paid",
          "state.cancelled": "Cancelled",
          "delivery.planned.to": "Estimated delivery",
          "customer.cash": "Cash",
          "client.delivery": "Deliver",
          "cash.collect": "Collected",
          "client.cash.delivery": "Deliver and collect",
          "client.cash.all": "collect money all",
          "total": "Total",
          "delivery.proof": "Proof of delivery",
          "cash.window": "Cash cash",
          "money": "Collection",
          "this.order": "This order",
          "other.balance": "Other balance",
          "amount.must.be.bellow.to": "Amount must be less than ",
          "zero.not.allowed": "The value 0 is not allowed",
          "adjust": "Adjust",
          "saleprice": "Sale price",
          "sale": "Solde",
          "visit": "Visit",
          "apply.adjust": "Apply adjustment",
          "price.is.updated.if.changed": "Prices are updated if changed",
          "info": "Information",
          "Language": "Language",
          "Language_system": "Language of the application",
          "Notifications": "Notifications",
          "notifications_alert": "System Alerts",
          "Posts": "Posts",
          "discussion_message": "Messages with users",
          "Theme": "Theme",
          "theme_system": "App Theme",
          "current_version": "Current Version",
          "your_warehouse": "My delivery warehouses",
          "disconnect_account": "Disconnect from your account",
          "dashboard": "Dashboard",
          "turnover": "Turnover",
          "category_turnover": "Turnover by category",
          "customer_classes": "Distribution of my clients",
          "Disponible": "Available",
          "others": "Others",
          "please select ...": "Please select...",
          "type_pv": "Type of PV",
          "sell": "Sell",
          "bluetooth": "Bluetooth",
          "Cart": "Cart",
          "Pcs": "Pcs",
          "Paquet": "Pack",
          "Caisse": "Box",
          "succefully.saved": "Your operation was successful",
          "OK": "OK",
          "read": "read",
          "unread": "unread",
          "new_order_placed": "Order placed to customer",
          "order_inpreparing": "Order is in preparation for deposit",
          "order_inway": "Order is in the process of being delivered",
          "order_delivered": "Order is delivered",
          "order_cashed": "Order Cashed",
          "order_cashed_partially": "Order is partially paid",
          "cash.money": "Cash amount",
          "empty.not.allowed": "Empty value is not allowed",
          "cash.erase.action": "Are you sure to pay all amount",
          "delivery.without.cash": "Are you sure to deliver without cashing",
          "receivables": "Receivables",
          "customers_balance": "Customers with their balances",
          "delivery.proof.is.required": "Delivery Proof is required",
          "my.coupons": "Coupons",
          "coupons.config": "Coupons Configuration",
          "more.than": "More than",
          "use.coupon": "Use Coupon",
          "coupon.window": "Enter your Coupon",
          "description.coupon":
              "The coupon is used to reduce the order amount, please enter your coupon code now",
          "ex.coupon": "ex: ABCDEFGH",
          "my.actors": "My Actors",
          "actor.config": "See all actors and configuration",
          "coupon": "Coupon",
          "no.more.coupon.available": "No more coupon available",
          "no.coupon.found": "No coupon for this code",
          "order.amount.must.be.more.than": "Order amount must be more than ",
          "coupon.settings": "Coupon settings",
          "code": "Code",
          "count": "Count",
          "modification.window": "Modification window",
          "max.value": "Maximum value is ",
          "comma.not.allowed": "Comma is nont allowed",
          "optimize.route": "Optimize route",
          "maps.route": "Go to maps",
          "cancel": "Cancel",
          "day.only": "Visit Day",
          "reason.no.sale": "Reasons for not selling",
          "status.orders": "Orders Status",
          "renew.order.question": "Are you sure to renew the order ?",
          "confirmation.renew": "Confirmation",
          "ask.confirm":"Do you want to confirm this operation ?",
        },
        "ar": {
          "year":"سنة",
          "loading":"جارٍ التحميل",
          "credit":"دين",
          "customers_credit":"دين العملاء",
          "commercial": "تجاري",
          "commercial.sub": "إدارة الأعمال",
          "welcome": "أهلاً بك",
          "to_our_service": "في خدمتنا",
          "slogan": "بيع أكثر، اربح أكثر!",
          "get_started": "البدء",
          "login": "تسجيل الدخول",
          "login_text": "أدخل بريدك الإلكتروني وكلمة المرور",
          "password_forgot": "هل نسيت كلمة المرور؟",
          "not_yet_user": "ليس لديك حساب حتى الآن؟",
          "signup": "التسجيل",
          "signup_text": "أدخل معلوماتك الشخصية",
          "create": "إنشاء حساب",
          "forget": "نسيت كلمة المرور",
          "forgot_text": "أدخل بريدك الإلكتروني لاستعادة كلمة المرور",
          "wrongemailaddress": "تنسيق عنوان البريد الإلكتروني غير صحيح",
          "emptypassword": "كلمة المرور لا يمكن أن تكون فارغة",
          "mailempty": "لا يمكن أن يكون البريد الإلكتروني فارغًا",
          "shortpassword": "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل",
          "nouserfound": "لم يتم العثور على أي حساب لهذا البريد الإلكتروني!",
          "wrongpassword": "كلمة المرور غير متطابقة مع هذا الحساب!",
          "fullname_length_error": "يرجى إدخال الاسم الكامل",
          "otherway": "أو عبر طرق أخرى",
          "success": "نجاح العملية",
          "registred.email":
              "تم إنشاء حسابك بنجاح...\nتم إرسال بريد تأكيد إلى عنوان البريد الإلكتروني الخاص بك.",
          "registred.social": "تم إنشاء حسابك بنجاح...",
          "verificationmail.title": "البريد الإلكتروني غير مفعل",
          "erroraccountexist": "هذا البريد الإلكتروني مسجل بالفعل!",
          "verificationmail.body":
              "لم يتم تفعيل حسابك حتى الآن!\nهل تريد إرسال بريد إلكتروني للتحقق؟",
          "find_product": "البحث عن المنتجات",
          "search": "بحث",
          "bestselling": "الأكثر مبيعًا",
          "products": "المنتجات",
          "categories": "الفئات",
          "general": "عام",
          "promotion": "الترقية",
          "Last Name": "اسم العائلة",
          "First Name": "الاسم الأول",
          "Wilaya": "ولاية",
          "City": "الدائرة",
          "Profile": "الملف الشخصي",
          "errorLastName": "يرجى إدخال اسم العائلة الخاص بك",
          "errorFirstName": "يرجى إدخال الاسم الأول الخاص بك",
          "errorWilaya": "يرجى تحديد ولايتك",
          "errorCity": "يرجى تحديد مدينتك",
          "errorProfile": "يرجى تحديد ملفك الشخصي",
          "profilesaved":
              "تم إجراء عملية الحفظ بنجاح. سيتم توجيهك إلى الصفحة الرئيسية!",
          "unknownerror":
              "حدثت مشكلة أثناء عملية الحفظ. يرجى المحاولة مرة أخرى لاحقًا.",
          "error": "خطأ",
          "userdisabled": "تم تعطيل حسابك!",
          "unknown.error": "حدث خطأ، يرجى المحاولة مرة أخرى في وقت لاحق",
          "email.used": "عنوان البريد الإلكتروني المرتبط بالفعل قيد الاستخدام!",
          "new.client": "زبون جديد",
          "edit.client": "تحرير الزبون",
          "name.client": "اسم الزبون",
          "type.client": "نوع الزبون",
          "mobile.client": "الهاتف",
          "editer.client": "تحرير الزبون",
          "error.name.client": "اسم الزبون مطلوب",
          "position.disabled.do.you.want.enable":
              "التطبيق لا يحصل على إذنك الحالي للحصول على موقعك. هل تريد منح الإذن؟",
          "position.forever.disabled":
              "تم رفض أذونات الموقع بشكل دائم. لا يمكننا طلب الأذونات.",
          "sendmail": "إرسال بريد",
          "mail.not.verified": "البريد الإلكتروني غير مفعّل",
          "save": "حفظ",
          "print": "طباعة",
          "empty.items": "إفراغ الطلب",
          "close": "إغلاق",
          "add": "إضافة",
          "are.you.sure.to.ignore": "هل أنت متأكد من تجاهل هذا الطلب؟",
          "are.you.sure.to.quit.order": "هل أنت متأكد من الخروج من هذا الطلب؟",
          "you.are.disconnected": "لديك مشكلة في الاتصال بالإنترنت",
          "quantity.not.available": "لا يتوفر أحد المنتجات في المخزون!",
          "successfully.saved": "تم حفظ عمليتك بنجاح.",
          "error.saved":
              "لم يتم تنفيذ عمليتك بشكل صحيح. يرجى المحاولة مرة أخرى.",
          "printer.config.title": "إعدادات الطابعة",
          "no printer!": "لا يوجد طابعة متصلة",
          "no.printer.found": "لم يتم العثور على طابعة!",
          "searching": "جار البحث...",
          "printer.size": "حجم الورق",
          "cities": "مدن",
          "edit.profile": "تحرير الملف الشخصي",
          "rescan": "البحث مجددًا",
          "printing": "جاري الطباعة!",
          "print.not_available": "لم يتم العثور على الطابعة!",
          "bluetooth.problem": "مشكلة في الاتصال اللاسلكي بالطابعة",
          "printer.pb.link": "مشكلة في الاتصال اللاسلكي بالطابعة",
          "printer.settings": "إعدادات الطابعة",
          "encoding": "ترميز",
          "size.subtitle": "حجم الفرع",
          "small": "صغير",
          "middle": "وسط",
          "saturday": "السبت",
          "sunday": "الأحد",
          "monday": "الإثنين",
          "tuesday": "الثلاثاء",
          "thursday": "الأربعاء",
          "wednesday": "الخميس",
          "friday": "الجمعة",
          "print.client.balance": "طباعة سجل الرصيد",
          "mywarehouses": "مستودعاتي",
          "disconnect": "الخروج",
          "about": "عن البرنامج",
          "reception.product": "استلام المنتجات",
          "print.stock": "طباعة حالة المخزون",
          "client.more.infos": "مزيد من المعلومات",
          "my.promotions": "عروضي",
          "promo.config": "تكوين العروض الترويجية",
          "to": "إلى",
          "edit": "تعديل",
          "new": "جديد",
          "new.promotion": "عرض ترويجي جديد",
          "edit.promotion": "تعديل العرض الترويجي",
          "description": "الوصف",
          "describe.your.promo.here": "وصف العرض الترويجي هنا",
          "discount_price": "على السعر",
          "discount_total": "على المجموع",
          "add.product": "إضافة منتج أو متغير",
          "product": "المنتج",
          "variant": "المتغير",
          "discount": "التخفيض",
          "minimum": "الحد الأدنى",
          "list.orders": "قائمة الطلبات",
          "send": "إرسال إلى",
          "export": "تصدير إلى PDF",
          "print.invoices.today": "طباعة الفواتير",
          "print.goods.today": "طباعة ملخص البضائع",
          "last.name": "اسم العائلة",
          "first.name": "الاسم الأول",
          "phone": "الهاتف",
          "errorPhone.empty": "هذا الحقل مطلوب",
          "errorPhone.notvalide": "رقم الهاتف غير صالح",
          "quantity": "الكمية",
          "orders.ready.toship": "الطلبات الجاهزة للشحن",
          "generate.bt": "إنشاء بون نقل",
          "refresh": "تحديث",
          "confirm.bt": "تأكيد بون النقل",
          "bl.ready": "التسليم",
          "bt.ready": "نقل البضائع",
          "location.stock": "المخزون الحالي",
          "dispo.only": "متاح",
          "alert.only": "تحت الإنذار",
          "empty.only": "نفذت الكمية",
          "all": "الكل",
          "transfer.is.ready.to.confirm": "البون النقل جاهز للتأكيد",
          "transfer.confirmed": "تم تأكيد البون النقل بنجاح",
          "orders.to.ship": "الطلبات المطلوب توصيلها",
          "orders.to.track": "حالة الطلبات",
          "settings": "الإعدادات",
          "track.order": "تتبع الطلب",
          "state.new": "جديد",
          "state.taken": "قيد التحضير",
          "state.in_way": "في الطريق",
          "state.shipped": "تم التوصيل",
          "state.expired": "منتهي الصلاحية",
          "state.paid": "تم الدفع",
          "state.partially_paid": "مدفوعة جزئيا",
          "state.cancelled": "ملغاة",
          "delivery.planned.to": "تاريخ التوصيل المتوقع",
          "client.cash": "الدفع نقداً",
          "client.cash.all": "دفع  جميع الطلبات",
          "client.delivery": "التوصيل",
          "cash.collect": "تم الدفع",
          "client.cash.delivery": "التوصيل والدفع نقداً",
          "total": "الإجمالي",
          "delivery.proof": "إثبات التوصيل",
          "cash.window": "نافذة الدفع",
          "money": "المبلغ",
          "this.order": "هذا الطلب",
          "other.solde": "رصيد آخر",
          "amount.must.be.bellow.to": "يجب أن يكون المبلغ أقل من ",
          "zero.not.allowed": "لا يسمح بالقيمة صفر",
          "adjust": "ضبط",
          "saleprice": "سعر البيع",
          "sale": "بيع",
          "visit": "زيارة",
          "apply.adjust": "تطبيق التعديل",
          "price.is.updated.if.changed": "يتم تحديث الأسعار في حالة التغيير",
          "info": "معلومات",
          "Language": "اللغة",
          "Language_system": "لغة التطبيق",
          "Notifications": "التنبيهات",
          "notifications_alert": "تنبيهات النظام",
          "Messages": "الرسائل",
          "discussion_message": "الرسائل مع المستخدمين",
          "Theme": "الثيم",
          "theme_system": "ثيم التطبيق",
          "current_version": "النسخة الحالية",
          "pormo.config": "تكوين العروض الترويجية",
          "your_warehouse": "مستودعات التسليم الخاصة بي",
          "disconnect_account": "قطع الاتصال بحسابك",
          "dashboard": "لوحة القيادة",
          "turnover": "العائدات",
          "category_turnover": "العائدات حسب الفئة",
          "customer_classes": "توزيع الزبائن",
          "Disponible": "متوفر",
          "others": "أخرى",
          "please select ...": "يرجى الاختيار...",
          "type_pv": "نوع نقطة البيع",
          "sell": "بيع",
          "bluetooth": "بلوتوث",
          "Cart": "كرتون",
          "Pcs": "قطع",
          "Paquet": "رزمة",
          "Caisse": "صندوق",
          "succefully.saved": "كانت عمليتك ناجحة",
          "OK": "موافق",
          "read": "مقروء",
          "unread": "غير مقروء",
          "new_order_placed": "تم تقديم الطلب للزبون",
          "order_inpreparing": "الطلب قيد التحضير للإيداع",
          "order_inway": "الطلب قيد التسليم",
          "order_delivered": "تم تسليم الطلب",
          "order_cashed": "تم صرف الطلب",
          "order_cashed_partially": "طلب مدفوع جزئيًا",
          "cash.money": "مبلغ نقدي",
          "empty.not.allowed": "القيمة الفارغة غير مسموح بها",
          "cash.erase.action": "هل أنت متأكد من دفع كل المبلغ",
          "delivery.without.cash": "هل أنت متأكد من التسليم دون صرف",
          "receivables": "المبالغ المستحقة القبض",
          "customers_balance": "الزبائن بأرصدتهم",
          "delivery.proof.is.required": "دليل التسليم مطلوب",
          "my.coupons": "كوبوناتي",
          "coupons.config": "تكوين الكوبونات",
          "more.than": "أكثر من",
          //"more...": "انظر التفاصيل",
          "use.coupon": "استخدم قسيمة",
          "coupon.window": "استخدم قسيمة",
          "description.coupon":
              "القسيمة تستخدم لتقليل مبلغ الطلب ، يرجى إدخال رمز القسيمة الخاص بك الآن",
          "ex.coupon": "مثال: ABCDEFGH",
          "my.actors": "البائعين الخاصين بي",
          "actor.config": "رؤية جميع الجهات الفاعلة والتشكيل",
          "coupon": "القسيمة",
          "no.more.coupon.available": "لا يتوفر المزيد من القسيمة",
          "no.coupon.found": "لا يوجد قسيمة لهذا الرمز",
          "order.amount.must.be.more.than": " يجب أن يكون مبلغ الطلب أكثر من",
          "coupon.settings": "إعدادات القسيمة",
          "code": "كود",
          "count": "عدد",
          "modification.window": "نافذة التعديل",
          "max.value": "القيمة القصوى هي ",
          "comma.not.allowed": "الفاصلة غير مسموح بها",
          "optimize.route": "الطريق الأمثل",
          "maps.route": "اذهب إلى الخرائط",
          "cancel": "إلغاء",
          "reason.no.sale": "أسباب عدم البيع",
          "status.orders": "حالة الطلبات",
          "renew.order.question": "هل أنت متأكد من تجديد الطلب ؟",
          "confirmation.renew": "تأكيد",
          "confirm": "تأكيد",
          "ask.confirm":"هل تريد تأكيد هذه العملية ؟",
        },
      };
}
